services:
    reservation-service:
        build: .
        ports:
            - "8003:8003"
        env_file:
            - .env
        environment:
            DB_HOST: reservation_db
            RABBITMQ_HOST: rabbitmq
        depends_on:
            - reservation_db
        networks:
            - crrs_network
        volumes:
            - .:/var/www

    reservation_db:
        image: postgres:15
        environment:
            POSTGRES_DB: crrs_reservation_db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret
        volumes:
            - reservation_db_data:/var/lib/postgresql/data
        networks:
            - crrs_network

networks:
    crrs_network:
        external: true

volumes:
    reservation_db_data:
